before_install:
  - sudo apt-get install build-essential

language: c

compiler:
  - clang

script:
  - export TESTDIR=$(pwd)/grf/testdata
  - rm -rf build/
  - mkdir build && cd build
  - cmake .. -DGRFLIB_BUILD_EXAMPLES=ON -DGRFLIB_BUILD_TESTS=ON
  - cmake --build .
  - ./grf/grf_test
  - ./grf/rgz_test
